@file:Suppress("PackageDirectoryMismatch")

object Versions {

    const val gradleVersion = "7.4.0"
    const val kotlinVersion = "1.9.22"
    const val googleServicesVersion = "4.4.1"
    const val crashAnalyticsPlugin = "2.9.9"
    const val zohoPlugin = "0.1-beta4"
    const val daggerHiltVersion = "2.48"
    const val sandwishVersion = "1.2.2"
    const val mpAndroidChartVersion = "3.1.0"
    const val lottieVersion = "5.2.0"
    const val truthVersion = "1.1.3"
    const val androidArchCoreTest = "2.1.0"
    const val coroutinesVersion = "1.6.2"
    const val ktlintVersion = "0.40.0"
    const val gradleVersionsPluginVersion = "0.39.0"
    const val composeViewModelVersion = "2.4.0-rc01"
    const val kotlinCompilerExtensionVersion = "1.5.10"
    const val linePageIndicator = "1.2.1"
    const val lifeycycleVersion_runtime = "2.4.0-alpha01"
    const val firebaseBomVersion = "32.8.1"
    const val timber_version = "5.0.1"
    const val stdlib_version = "1.5.21"
    const val rxandroid = "3.0.0"
    const val koin = "3.2.0"
    const val rxjava3 = "3.1.3"
    const val rxKotlin = "3.0.1"
    const val CORE = "1.7.10"
    const val COROUTINES = "1.6.3"
    const val ATOMICS = "0.18.3"
    const val zohoBom = "0.1-beta5"
    const val KSP = "1.9.22-1.0.17"
    // data
    const val AZURE = "2.0.0@aar"
    const val glide = "4.12.0"
    const val COIL = "2.5.0"
    const val roomVersion = "2.4.0"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.9.2"
    const val moshiVersion = "1.13.0"
    const val retrofitGson = "2.9.0"
    const val gsonVersion = "2.8.9"
    const val datastoreVersion = "1.0.0"
    const val PROTO_BUF = "0.8.17"
    const val PROTO_BUF_LITE = "3.0.1"
    const val GRPC = "1.45.1"
    //ui
    const val PAGINATION = "3.1.1"
    const val composeVersion = "1.0.4"
    const val composeActivityVersion = "1.7.2"
    const val composeNavigationVersion = "2.2.2"
    const val legacy = "1.0.0"
    const val appCompatVersion = "1.4.1"
    const val materialVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.3"
    const val swipeRefreshLayoutVersion = "1.1.0"
    const val DATE_TIME = "0.3.2"
    const val composeConstraintLayoutVersion = "1.0.0-beta02"
    const val accompanistSwipeRefresh = "0.21.0-beta"
    const val hiltNavigationCompose = "1.0.0-alpha03"
    const val navigationComponent = "2.3.5"
    const val animation = "2.4@aar"
    const val lifeycycleVersion = "2.8.0-alpha02"
    const val ACTIVITY_X = "1.8.2"
    const val WEB_BROWSER = "1.5.0"
    const val SPLASH = "1.0.0-alpha02"
    const val picassoVersion = "2.71828"
    const val PAGINATION_COMPOSE = "1.0.0-alpha17"
    const val media3_version = "1.3.1"
    const val ANNOTATION_JAVAX = "1.3.2"
    const val GOOGLE_MAP = "2.11.4"
    const val GOOGLE_MAP_PLACES= "3.1.0"
    const val GOOGLE_MAP_UTILS = "2.11.2"
    // testing

    const val junit4Version = "4.13.2"
    const val junitExtensionsVersion = "1.1.3"
    const val espressoCoreVersion = "3.4.0"
    const val mockkVersion = "1.12.0"
    const val robolectricVersion = "4.6.1"

    object Android {
        const val COMPOSE = "1.6.0-alpha01"
        const val COMPOSE_UTIL = "1.5.4"
        const val COMPOSE_DESTINATION = "1.7.25-beta"
        const val CONSTRAINT_LAYOUT = "1.0.1"
        const val APPCOMPAT = "1.4.2"
        const val MATERIAL = "1.6.1"
        const val MATERIAL3 = "1.2.1"
        const val NAVIGATION = "2.5.1"
        const val VIEW_MODEL = "2.5.1"
        const val CORE_KTX = "1.9.0"
        const val COLLECTION_KTX = "1.2.0"
        const val ACTIVITY_KTX = "1.4.0"
        const val FRAGMENT_KTX = "1.5.0"
        const val PALETTE_KTX = "1.0.0"
        const val WORKER_KTX = "2.7.1"
        const val HILT_WORKER_KTX = "1.0.0"
        const val ACCOMPANIST_PAGER = "0.23.1"
        const val ACCOMPANIST_PAGER_INDICATORS = "0.23.1"
        const val ACCOMPANIST_SYSTEM_UI = "0.26.2-beta"
        const val OTP_VIEW = "1.0"
        const val ACTIVITY = "1.7.1"
        const val accompanistPermissionsVersion = "0.23.1"

    }

    object Injection {
        const val DAGGER = "2.42"
        const val COMPOSE = "1.0.0"
    }

}
